[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@openzeppelin-upgrades/=lib/openzeppelin-contracts-upgradeable/'
]

[rpc_endpoints]
mumbai = "https://rpc.ankr.com/polygon_mumbai"